
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Then it was commited. It is here to support the old architecture.
 * If you use the new architecture, this file won't be included and instead will be generated by the codegen.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

 package com.reactnativesavedialog;

 import com.facebook.proguard.annotations.DoNotStrip;
 import com.facebook.react.bridge.Promise;
 import com.facebook.react.bridge.ReactApplicationContext;
 import com.facebook.react.bridge.ReactContextBaseJavaModule;
 import com.facebook.react.bridge.ReactMethod;
 import com.facebook.react.bridge.ReactModuleWithSpec;
 import com.facebook.react.bridge.ReadableArray;
 import com.facebook.react.bridge.ReadableMap;
 
 public abstract class NativeSaveDialogSpec extends ReactContextBaseJavaModule implements ReactModuleWithSpec {
   public NativeSaveDialogSpec(ReactApplicationContext reactContext) {
     super(reactContext);
   }
 
   @ReactMethod
   @DoNotStrip
   public abstract void saveFile(ReadableMap options, Promise promise);
 
   @ReactMethod
   @DoNotStrip
   public abstract void releaseSecureAccess(ReadableArray uris, Promise promise);
 }
 